sudo: required
services:
  - docker
script:
  - docker build -t mozamimy/fukafuka .
env:
  REPOSITORY: mozamimy/fukafuka
after_success:
  - if [ "$TRAVIS_TAG" != "" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
    docker tag $REPOSITORY $REPOSITORY:`cat VERSION` &&
    docker push $REPOSITORY:`cat VERSION` &&
    docker tag $REPOSITORY $REPOSITORY:latest &&
    docker push $REPOSITORY:latest ;
    fi
notifications:
  on_success: always
  on_failure: always
  on_start: false
